language: c
os: linux
dist: xenial

compiler:
  - gcc

install:
  - sudo pip install --ignore-installed conan
  - conan user

before_script:
  - cd test_package

script:
  - conan install .
  - cmake . -G "Unix Makefiles"
  - make all
  - make test
